[phases.setup]
nixPkgs = ["nodejs", "postgresql", "openssl", "curl", "xvfb", "chromium", "fontconfig", "ca-certificates", "fonts-liberation", "fonts-noto", "fonts-noto-cjk"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "NODE_ENV=production node dist/index.js"
onlyIncludeFiles = ["dist/**", "node_modules/**", "uploads/**", "server/assets/**", ".env.production"]

[variables]
DATABASE_URL = "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

[phases.setup.environment]
PORT = 5000
NODE_ENV = "production"

# Health check configuration
[[headers]]
path = "/api/health"
headers = { "Cache-Control" = "no-cache" }